language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="http://repo.continuum.io/miniconda/Miniconda-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: u/jLmlJZnyPeBY9R+UAxDqkTi1JnUVCoP3PEHrd9L1lL7jjd8fsdifdZ5P67TyKvMgfbuaoB5+2EwYP68yB8vovuEy2Xnlmjm1C8znN+veIhjZr5Hfc6O0Wod+hWk7srGmToW7qbZVZkpaas2vzsBBSap8iy+BTpwuBHIUieIYy6lbw7IWJ+QyNoXtSbfCY/mwxTuJYFeI3Z/ddYUPnMB/NWc8KtvN2H8Fpt9Z/cqp4JzZUP44C6xuYaZg/Wktpjsdo424sDxR5NA+Qp2cljIgh6GuL5keeRmwnnt0Lwf7lHQI1On16Y5FYMnrwJLciv8tjFd3tChn3WFEx85rpULkfSuljjLZE0T5t8c9jP7kY+XgnkpK27nuEnPMp+iwTOfd789SUiQ2QV8/Q8WaU11oaddr9zY9YlL7J6S7Mb3GhAGvZcnjZi8DCtTxrzR4u0BeiYC0qOYXQlY7CW40YUD9W8+CY6PUfMPHVFNOaPgjIWfys1ulEXGcqLQe7t2a1MlJwyoIaIo3Dp1ksGmSVGXZibvKeSFgKd/CwQJsi1FbLdWRKSNoaV3dkD2eJ3/BAcuZywoXi13Q3qVOkXF6kWBbH4MhJnrM+hgC7X60aAp9QJ4oLsde+Rxn+98yBe38k4+T/VOHDHdIK37jq0t5YhZxY1ZLS1VY577bELtSwtJio=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
